### ISSUE TITLE
Hi PETE !!

### ISSUE THREAD

**Issue by Rota66** [Petewg/MgM#4]
How are U ??

Any news about the possibility of a MgM 17.12 version ?
64bits & Mingw 7.2 ...
I know I would lost my 32 bits DLL ( Twain, etc...)

Meanwhile, I still with the 17.06u2 version.

Kind regards and a happy new year !!;

Thank U !

**Comment by Petewg** [comment]
Hi Rota66,
I consider the 17.06u2 version as the last stable release, that I can **trust** for production and that's what I do use currently.

Minigui team, (Grigory et al.) have made interesting new updates that "touch" several parts of library's **internals**. From my tests they seems to be Ok, however I see no special need to sychronize MgM with them and given the lack of free time I'm not sure yet if they'd worth the effort by now. Of course I plan to prepare an update in future, perhaps during Jan or Feb 2018.

As for 64 bits, I have no great interest, mainly because of the reason you mentioned (compatibility with 32bits dlls) plus that I cannot maintain double versions (32/64) of my applications, so for the foreseeable future I believe 32bits are just fine. IMHO the benefits of 64bits do not seem to be so many, to justify the transition. Maybe sometime in next years it will be compulsory such a move but not now. 

thanks for your wishes, Happy New Year to you too.
(btw, where are you from?)

regards,
Pete

**Comment by Rota66** [comment]
Hi Pete,

Sincerely I agree with your concerns.  
Your MGM compiled with Harbour 3.4 is the best version available ... Unfortunately, Grigory insists on the BCC version.  I have Xharbour.COM Enterprise version, but I prefer Harbour 3.4 for all the solutions and updates provided by Victor. 

What 32 Bits DLL you depend on for your systems? I only use TWAIN32 for camera/image acquisition. But I'm looking for 64 bits similar solution or a converter/parser 32-64 ...

By the way,

I'm Antonio Lima from the sunny south of BRAZIL.

regards,

Antonio

**Comment by Petewg** [comment]
just updated to 18.01..
